---
- name: OpenResty bootstrap
  hosts: proxy
  any_errors_fatal: false
  become: yes
  gather_facts: no

  roles:
# Install OpenResty from source
    - role: openresty-source
      tags: resty-source-install
# Configure and install custom module
    - role: filebeat
      tags: filebeat-install