---
- name: OpenResty bootstrap
  hosts: proxy
  any_errors_fatal: false
  # gather_facts: no
  # delegate_to: localhost

  roles:
# Install OpenResty from repo
    - role: openresty-repo
      tags: openresty-install
# Download source code release
    - role: openresty-modules
      tags: openresty-configure
# Configure and install custom module
    - role: filebeat
      tags: filebeat-install