---
- name: Configuring OpenResty source with custom modules
  become: yes
  shell: "./configure {{ nginx_custom_modules }}"
  args:
    chdir: "{{ nginx_install_dir }}"
  when: nginx_source_unpack|changed
  register: nginx_configure

- name: Make OpenResty
  become: yes
  shell: make
  args:
    chdir: "{{ nginx_install_dir }}"
  when: nginx_configure|changed

- name: Make install OpenResty
  become: yes
  shell: make install
  args:
    chdir: "{{ nginx_install_dir }}"
  when: nginx_configure|changed