---
# Installing Dependencies
- name: Installing OpenResty Dependencies
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - libssl-dev
    - zlib1g-dev
    - libpcre3
    - libpcre3-dev
    - unzip
    - wget 
    - gnupg 
    - ca-certificates
    - build-essential
    - libxslt-dev
    - libgd-dev
    - libgeoip-dev

# Install from repo
- name: Add apt key
  become: yes
  apt_key:
    url: https://openresty.org/package/pubkey.gpg
    state: present
  register: import_key

- name: Add Ubuntu apt repository
  become: yes
  apt_repository:
    repo: "deb http://openresty.org/package/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} main"
    state: present
  when: ansible_distribution == 'Ubuntu'

- debug: msg="{{ansible_distribution}}"

- name: Add Debian apt repository
  become: yes
  apt_repository:
    repo: "deb http://openresty.org/package/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} openresty"
    state: present
  when: ansible_distribution == 'Debian'

- name: Install OpenResty
  become: yes
  apt:
    name: openresty
    state: present
    update_cache: yes
    install_recommends: "no"
  notify: restart-openresty